### PR TITLE
doc auto-deploy via travis

### PR DESCRIPTION
**Pull request by iblis17**
@milktrader I need your help to deal with deploy key[1]. I do not have permission to add it.
After the key be added, please merge this PR. Documenter only push to `gh-pages` on `master` branch built or we push a new tag.
I have tried this PR on my forked repo[2].

1. https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html#SSH-Deploy-Keys-1
2. https://apclab.github.io/MarketTechnicals.jl/latest/

### CODE REVIEW

**Comment by milktrader** [comment]
Sorry for the delay, looking at this today.

**Comment by milktrader** [comment]
Keys added to github and travis

**Comment by milktrader** [comment]
Egads I hope I didn't leave whitespaces 😬

**Comment by iblis17** [comment]
auto-deploy works fine! https://juliaquant.github.io/MarketTechnicals.jl/latest/index.html
🎉 🎉

**Comment by milktrader** [comment]
Wow, very nice @iblis17 !

**Pull request merged**
