### PR TITLE
Updated module for Julia v1.1 and TS v0.14

### PR DESCRIPTION
**Pull request by shivchawla**
Could you please review the changes?
1. Updated the syntax to use Julia v1.1 and TS v0.14
2. Added more technical indicators

### CODE REVIEW

**Comment by iblis17** [comment]
ah, cc me

**Comment by iblis17** [comment]
Could you split this PR into two PRs?
The first part is about upgrading to Julia v1.x, and the second part is about adding new features.
Let's upgrade to Julia v1.x first, make sure no test cases failed,
and then adding new features.

If you need help on splitting your commits, I can help you.

**Comment by iblis17** [comment]
Is your branch writable for me?
I cannot determine that options enabled or not on my GitHub view.

**Comment by astadmistry** [comment]
Hi, any update on this PR?

**Pull request closed without merging**
